# Generated by Django 3.1.7 on 2021-06-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_remove_user_birthday'),
        ('snacks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='dislikes',
            field=models.ManyToManyField(related_name='displiked_snacks', to='login_app.User'),
        ),
        migrations.AddField(
            model_name='snack',
            name='likes',
            field=models.ManyToManyField(related_name='liked_snacks', to='login_app.User'),
        ),
    ]
